### ISSUE TITLE
GameControllerSimulator command line option to load specific game.json file

### ISSUE THREAD

**Issue by omichel** [RoboCup-Humanoid-TC/GameController#106]
In order to share the same `game.json` file between the `AutoReferee` and the `GameControllerSimulator`, it would be convenient to be able to pass the `game.json` file as an argument of the `GameControllerSimulator`, like:
```
java - jar GameControllerSimulator.jar /path/to/my/own/resources/config/game.json
```

**Comment by MaikePaetzel** [comment]
I agree - I think if an argument is given to the jar, then it should use that as the game config, otherwise, it can try to default back to the one in the resources folder. I'll add that in the next version.

**Comment by MaikePaetzel** [comment]
This was resolved in the latest commit.  You can now add a config using --config or -c

**Comment by omichel** [comment]
I now use this option from the referee and it works great. Thank you.
