### ISSUE TITLE
GameControllerSimultor doesn't always answer

### ISSUE THREAD

**Issue by omichel** [RoboCup-Humanoid-TC/GameController#108]
In order to try to understand why the referee was hanging while communicating with the GameControllerSimulator, I found that it is not responding under some circumstances. For example, with the following test program:

```python
#!/usr/bin/env python3

import socket
import time

HOST = '127.0.0.1'  # The server's hostname or IP address
PORT = 8750        # The port used by the server

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((HOST, PORT))
    start = time.time()
    ready, set, play, penalized, scored, kickoff = False, False, False, False, False, False
    message_numb = 0

    while True:
        delta = time.time() - start
        if delta > 1 and not kickoff:
            kickoff = True
            message = f"{message_numb}:SIDE_LEFT:26\n"
        elif delta > 3 and not ready:
            ready = True
            message = f"{message_numb}:STATE:READY\n"
        elif delta > 7 and not set:
            set = True
            message = f"{message_numb}:STATE:SET\n"
        elif delta > 12 and not play:
            play = True
            message = f"{message_numb}:STATE:PLAY\n"
        elif delta > 15 and play and not penalized:
            penalized = True
            message = f"{message_numb}:PENALTY:27:1:BALL_MANIPULATION\n"
        elif delta > 17 and play and not scored:
            scored = True
            message = f"{message_numb}:SCORE:27\n"
        else:
            message = f'{message_numb}:CLOCK:{int(delta * 3 * 1000)}\n'

        s.sendall(message.encode('ascii'))
        print(f'Sent: {message[:-1]}')

        data = s.recv(1024)
        if data:
            print(f"Received: {data}\n")
        else:
            print("Received nothing")

        message_numb += 1
        time.sleep(0.2)
```

It will hang after the following output:
```
Sent: 0:CLOCK:0
Received: b'0:OK'

Sent: 1:CLOCK:626
Received: b'1:OK'

Sent: 2:CLOCK:1250
Received: b'2:OK'

Sent: 3:CLOCK:1873
Received: b'3:OK'

Sent: 4:CLOCK:2476
Received: b'4:OK'

Sent: 5:SIDE_LEFT:26
```

Which seems to be that we never get the answer for the `SIDE_LEFT` message.
If I break the python program and restart it, it seems to work again and I receive the acknowledgement for the previous message ID 5 (which should probably be cleared after a connection is broken):

```
Sent: 0:CLOCK:0
Received: b'5:OK'

Sent: 1:CLOCK:608
Received: b'0:OK'

Sent: 2:CLOCK:1253
Received: b'1:OK'

Sent: 3:CLOCK:1894
Received: b'2:OK'

Sent: 4:CLOCK:2500
Received: b'3:OK'

Sent: 5:SIDE_LEFT:26
Received: b'4:OK'

Sent: 6:CLOCK:3753
Received: b'5:OK'

Sent: 7:CLOCK:4392
Received: b'6:OK'

Sent: 8:CLOCK:5004
Received: b'7:OK'

Sent: 9:CLOCK:5609
Received: b'8:OK'

Sent: 10:CLOCK:6215
Received: b'9:OK'

Sent: 11:CLOCK:6860
Received: b'10:OK'

Sent: 12:CLOCK:7462
Received: b'11:OK'

Sent: 13:CLOCK:8065
Received: b'12:OK'

Sent: 14:CLOCK:8671
Received: b'13:OK'

Sent: 15:STATE:READY
Received: b'14:OK'

Sent: 16:CLOCK:9918
Received: b'15:OK'

Sent: 17:CLOCK:10521
Received: b'16:OK'

Sent: 18:CLOCK:11126
Received: b'17:OK'

Sent: 19:CLOCK:11771
Received: b'18:OK'

Sent: 20:CLOCK:12415
Received: b'19:OK'

Sent: 21:CLOCK:13054
Received: b'20:OK'

Sent: 22:CLOCK:13699
Received: b'21:OK'

Sent: 23:CLOCK:14304
Received: b'22:OK'

Sent: 24:CLOCK:14910
Received: b'23:OK'

Sent: 25:CLOCK:15513
Received: b'24:OK'

Sent: 26:CLOCK:16154
Received: b'25:OK'

Sent: 27:CLOCK:16796
Received: b'26:OK'

Sent: 28:CLOCK:17441
Received: b'27:OK'

Sent: 29:CLOCK:18043
Received: b'28:OK'

Sent: 30:CLOCK:18649
Received: b'29:OK'

Sent: 31:CLOCK:19261
Received: b'30:OK'

Sent: 32:CLOCK:19863
Received: b'31:OK'

Sent: 33:CLOCK:20466
Received: b'32:OK'

Sent: 34:STATE:SET
Received: b'33:OK'

Sent: 35:CLOCK:21755
Received: b'35:OK'

Sent: 36:CLOCK:22370
Received: b'34:OK'

Sent: 37:CLOCK:22981
Received: b'36:OK'

Sent: 38:CLOCK:23596
Received: b'37:OK'

Sent: 39:CLOCK:24199
Received: b'38:OK'

Sent: 40:CLOCK:24840
Received: b'39:OK'

Sent: 41:CLOCK:25455
Received: b'40:OK'

Sent: 42:CLOCK:26097
Received: b'41:OK'

Sent: 43:CLOCK:26741
Received: b'42:OK'

Sent: 44:CLOCK:27386
Received: b'43:OK'

Sent: 45:CLOCK:28028
Received: b'44:OK'

Sent: 46:CLOCK:28660
Received: b'45:OK'

Sent: 47:CLOCK:29263
Received: b'46:OK'

Sent: 48:CLOCK:29869
Received: b'47:OK'

Sent: 49:CLOCK:30477
Received: b'48:OK'

Sent: 50:CLOCK:31083
Received: b'49:OK'

Sent: 51:CLOCK:31727
Received: b'50:OK'

Sent: 52:CLOCK:32333
Received: b'51:OK'

Sent: 53:CLOCK:32972
Received: b'52:OK'

Sent: 54:CLOCK:33574
Received: b'53:OK'

Sent: 55:CLOCK:34183
Received: b'54:OK'

Sent: 56:CLOCK:34795
Received: b'55:OK'

Sent: 57:CLOCK:35406
Received: b'56:OK'

Sent: 58:STATE:PLAY
Received: b'57:OK'

Sent: 59:CLOCK:36651
Received: b'59:OK'

Sent: 60:CLOCK:37262
Received: b'58:OK'

Sent: 61:CLOCK:37907
Received: b'60:OK'

Sent: 62:CLOCK:38513
Received: b'61:OK'

Sent: 63:CLOCK:39157
Received: b'62:OK'

Sent: 64:CLOCK:39763
Received: b'63:OK'

Sent: 65:CLOCK:40377
Received: b'64:OK'

Sent: 66:CLOCK:41022
Received: b'65:OK'

Sent: 67:CLOCK:41628
Received: b'66:OK'

Sent: 68:CLOCK:42236
Received: b'67:OK'

Sent: 69:CLOCK:42839
Received: b'68:OK'

Sent: 70:CLOCK:43445
Received: b'69:OK'

Sent: 71:CLOCK:44050
Received: b'70:OK'

Sent: 72:CLOCK:44695
Received: b'71:OK'

Sent: 73:PENALTY:27:1:BALL_MANIPULATION
Received: b'72:OK'

Sent: 74:CLOCK:45909
Received: b'74:OK'

Sent: 75:CLOCK:46518
Received: b'73:OK'

Sent: 76:CLOCK:47157
Received: b'73:OK'

Sent: 77:CLOCK:47801
Received: b'75:OK'

Sent: 78:CLOCK:48404
Received: b'76:OK'

Sent: 79:CLOCK:49049
Received: b'77:OK'

Sent: 80:CLOCK:49654
Received: b'78:OK'

Sent: 81:CLOCK:50296
Received: b'79:OK'

Sent: 82:CLOCK:50901
Received: b'80:OK'

Sent: 83:SCORE:27
Received: b'81:OK'

Sent: 84:CLOCK:52158
Received: b'82:OK'

Sent: 85:CLOCK:52760
Received: b'84:OK'

Sent: 86:CLOCK:53381
Received: b'83:ILLEGAL'

Sent: 87:CLOCK:53984
Received: b'85:OK'

Sent: 88:CLOCK:54598
Received: b'86:OK'

Sent: 89:CLOCK:55213
Received: b'87:OK'

Sent: 90:CLOCK:55858
Received: b'88:OK'

Sent: 91:CLOCK:56460
Received: b'89:OK'

Sent: 92:CLOCK:57066
Received: b'90:OK'

Sent: 93:CLOCK:57675
Received: b'91:OK'

Sent: 94:CLOCK:58286
Received: b'92:OK'

Sent: 95:CLOCK:58898
Received: b'93:OK'

Sent: 96:CLOCK:59504
Received: b'94:OK'

Sent: 97:CLOCK:60148
Received: b'95:OK'

Sent: 98:CLOCK:60793
Received: b'96:OK'

Sent: 99:CLOCK:61437
Received: b'97:OK'

Sent: 100:CLOCK:62040
Received: b'98:OK'

Sent: 101:CLOCK:62682
Received: b'99:OK'

Sent: 102:CLOCK:63323
Received: b'100:OK'

Sent: 103:CLOCK:63926
Received: b'101:OK'

Sent: 104:CLOCK:64565
Received: b'102:OK'

Sent: 105:CLOCK:65170
Received: b'103:OK'

Sent: 106:CLOCK:65776
Received: b'104:OK'

Sent: 107:CLOCK:66418
Received: b'105:OK'

Sent: 108:CLOCK:67020
Received: b'106:OK'

Sent: 109:CLOCK:67665
Received: b'107:OK'

Sent: 110:CLOCK:68310
Received: b'108:OK'

Sent: 111:CLOCK:68951
Received: b'109:OK'

Sent: 112:CLOCK:69554
Received: b'110:OK'

Sent: 113:CLOCK:70162
Received: b'111:OK'

Sent: 114:CLOCK:70804
Received: b'112:OK'

Sent: 115:CLOCK:71413
Received: b'113:OK'

Sent: 116:CLOCK:72036
Received: b'114:OK'

Sent: 117:CLOCK:72648
Received: b'115:OK'

Sent: 118:CLOCK:73290
Received: b'116:OK'
```

**Comment by omichel** [comment]
Thank you for the explanation.

I was not expecting such an asynchronous behavior from the GameController. My initial naive implementation was simply sending the SIDE_LEFT, KICKOFF and STATE messages before starting to send CLOCK messages every 8 virtual milliseconds (e.g., ~24 real milliseconds), but that didn't worked as I was not receiving synchronous answers for the first 3 messages.

Supporting this asynchronous protocol means making the socket connection of the referee non-blocking for receiving data and assuming answers for a given message can arrive late and possibly in the wrong order. This shouldn't be a problem as I suppose the OK answers can be simply ignored and the ILLEGAL and INVALID answers should be used only for debugging purposes and shouldn't require any other handling than simply printing an error message in the console to help debugging the referee. If so, I believe I can make the referee handle this asynchronous protocol even though it will add complexity to the code. But, that would require no modification on the GameController side.

I will post back here whenever I achieve a working solution.

**Comment by MaikePaetzel** [comment]
I agree that the ILLEGAL and INVALID messages are mostly for debugging purposes and should probably also be stored in the log files of the AutoRef, just in case something unexpected happens during the tournament so it allows for easier debugging. I will add this to the log files of the GameController as well, just to make sure. With CLOCK updates every 24 real milliseconds, I think the implementation as-is on the GC side should be the safest option to go with because some internal processes like switching sides have a longer computation time than 24 ms, and this way we make sure that the internal processes always stay up to date with the game time.

Looking forward to your updates on this!

**Comment by omichel** [comment]
I turns out that the answers from the GameController are pretty difficult to parse, especially because messages are sometimes concatenated, for example, I receive from time to time a message like `652:OK653:OK`. I would be very helpful and probably easy to add a carriage return in the GameController so that I would get `652:OK\n653:OK\n` instead, which is easier to parse.

**Comment by MaikePaetzel** [comment]
> I turns out that the answers from the GameController are pretty difficult to parse, especially because messages are sometimes concatenated, for example, I receive from time to time a message like `652:OK653:OK`. I would be very helpful and probably easy to add a carriage return in the GameController so that I would get `652:OK\n653:OK\n` instead, which is easier to parse.

That's right, I updated the PR accordingly. I also added the INVALID message in case a message type is unknown to the GameController.

**Comment by MaikePaetzel** [comment]
> However, this doesn't seem to crash the GameController, so maybe it could be ignored? I just wanted to make sure there isn't a bug in the GameController about it. Any idea?

It looks like you are trying to hand the kickoff to a team that is not playing (otherwise I don't see how this exception would be thrown). I agree that this should be properly handled by the GC, I'll add that case. In the meantime, could you share the config file you are using to play?

**Comment by omichel** [comment]
Thank you. I just adapted the code to the new version (that include `\n`) and it works nicely. However, the Java exception remains.

**Comment by MaikePaetzel** [comment]
Okay the problem was a bug in the KidSize setup in the GameController, which wasn't properly caught because the GameController would just use a default team if no valid team number was provided during setup. Now an exception is thrown if the team numbers set in the game.json are invalid and a message is also rejected if a command is performed on a team currently not playing. This should fix the errors you reported - I tried to play with the game.json you linked and it works just fine now.

**Comment by omichel** [comment]
There is still one missing carriage return in the answers from the GameControllerSimulator, see my [patch](https://github.com/sheepsy90/GameController/pull/2).

**Comment by MaikePaetzel** [comment]
Thanks for spotting that, I've merged it!
