### ISSUE TITLE
Typo in gamestate.py?

### ISSUE THREAD

**Issue by omichel** [RoboCup-Humanoid-TC/GameController#109]
This looks wrong:

https://github.com/RoboCup-Humanoid-TC/GameController/blob/master/protocols/python/gamestate.py#L65

Shouldn't it be renamed to "kickoff_team" instead?

**Comment by MaikePaetzel** [comment]
I agree, but this is the standard protocol used by the teams, so changing this would require all teams to adapt their parsing of the protocol - so I'm inclined to leave it as is.

**Comment by omichel** [comment]
OK, FYI I fixed the typo in my own version of `gamestate.py` which I forked as discussed.
