### ISSUE TITLE
Heartbeat for AutoRef?

### ISSUE THREAD

**Issue by MaikePaetzel** [RoboCup-Humanoid-TC/GameController#111]
Discuss and potentially implement a heartbeat for the AutoReferee to send to the GameController.

**Comment by omichel** [comment]
I totally removed the sending of the heartbeat from the referee to the GameController on UDP port 3939 and I am still receiving the updates of the GameController on UDP port 3838 normally. I am not sure why this didn't seem to work before. But the problem appears to be resolved now.

**Comment by MaikePaetzel** [comment]
Okay, great to hear.
