### ISSUE TITLE
Add a possibility for teams to change the goalkeeper

### ISSUE THREAD

**Issue by MaikePaetzel** [RoboCup-Humanoid-TC/GameController#113]
Teams need to be able to send a message to the GameController to indicate that another robot is now playing as goalkeeper.

**Comment by medrimonia** [comment]
In order to be able to take into account all the rules, the AutoReferee should also be made aware of this information. This will imply to update the GameState message right?

**Comment by MaikePaetzel** [comment]
Correct, we will add a flag for GoalKeeper to each robot.

**Comment by MaikePaetzel** [comment]
Has been addressed in PR #137
