### ISSUE TITLE
Bug in remaining seconds report in gamestate

### ISSUE THREAD

**Issue by MaikePaetzel** [RoboCup-Humanoid-TC/GameController#114]
Reported by Olivier:

> from time to time it will send a gamestate.remaining_seconds == 600 (10 minutes) in the middle of the PLAYING state where it should be lower.

**Comment by MaikePaetzel** [comment]
@omichel can you provide a message log of what you are sending and receiving for this to happen?

**Comment by omichel** [comment]
It happens only by the end of the first half, when about two minutes of play are remaining.
Here is the log I have:
[log.zip](https://github.com/RoboCup-Humanoid-TC/GameController/files/6277556/log.zip)

**Comment by medrimonia** [comment]
I wonder if this is related, but I also found that sometimes incoherent messages appear when using `--fast` mode. I had the following sequence of `secondary_seconds_remaining` in messages when using it:

```
    secondary_seconds_remaining = 10
    secondary_seconds_remaining = 10
    secondary_seconds_remaining = 0
    secondary_seconds_remaining = 9
    secondary_seconds_remaining = 9
 ```

**Comment by omichel** [comment]
Yes, I could also observe this from time to time and I suspect this is confusing the referee. That seems to be a bug of the GameController similar to the "600 seconds remaining".

**Comment by MaikePaetzel** [comment]
@omichel Can you confirm that the latest commit also fixed it for you?

**Comment by omichel** [comment]
I am testing right now and it seems the 600 remaining seconds bug is gone, and the one with secondary remaining seconds seems also pretty much fixed.
It happens sometimes however that the secondary remaining seconds sequence drops from 2 to 0 without passing by the 1, but that's maybe because I am running the tests in fast mode. Anyhow I am introducing some code in the referee that will monitor this bug and display an error message if something wrong is spotted.
I will commit this right after I finished tests.

**Comment by omichel** [comment]
Done [here](https://github.com/cyberbotics/webots/pull/3012/commits/21a1b9159f8dc151c9e2b04fd5e714a1c558d28c).

**Comment by MaikePaetzel** [comment]
Yeah, I've noticed it skipping seconds as well (not just 2 to 0, but also somewhere in between) - however only when run faster than realtime, so I would assume this is an issue that in some conditions preparing and sending the message takes longer, so we are skipping one intermediate message to be sent. But with the fix, at least we are making sure that we are just skipping that intermediate message in this case and not send a message with invalid numbers instead.

**Comment by MaikePaetzel** [comment]
I'm closing this issue now. Please re-open if you find this still being a problem
