### ISSUE TITLE
Dynamic CoachMessage Size

### ISSUE THREAD

**Issue by sheepsy90** [RoboCup-Humanoid-TC/GameController#12]
Check if it is a good design decision to add a field coachMessageLength that expresses how long the 
following coachMessage is.

**Comment by sheepsy90** [comment]
Benefits: Much smaller package size

**Comment by robocup-hl-tc** [comment]
That should not be done currently due to the fixed UDP Package Size. One would rather need to check if we can somehow solve the issue of seperating or specializing the protocol for the HL and SPL with other measures.
