### ISSUE TITLE
Extended time only possible when goal count > 0?

### ISSUE THREAD

**Issue by MaikePaetzel** [RoboCup-Humanoid-TC/GameController#126]
In the current implementation, it is only possible to go to an extended time if there was more than one goal scored in the game. I don't think this is in accordance with our rule book. Shall it be changed?

**Comment by medrimonia** [comment]
My understanding is that the current rules do not define what methods are used to solve a draw. It just mentions what are the 'allowed' methods to do so.
So I think that this choice can be done for each competition and personally, I would prefer to see it changed to make extended time automatic, even if there is no goal.

**Comment by MaikePaetzel** [comment]
Okay, this will be updated then.

**Comment by omichel** [comment]
Okay, so I will assume that the referee should start the extended time in a KNOCKOUT game even if there is no goals.

**Comment by MaikePaetzel** [comment]
Has been addressed in PR #137
