### ISSUE TITLE
Dynamic RobotInfo Size

### ISSUE THREAD

**Issue by sheepsy90** [RoboCup-Humanoid-TC/GameController#13]
Check if it is a good design decision to add a field numRobots in the TeamInfo that specifies how many robots the team has. Additionally one can add a field isFirstRobotCoach that is true or false whether the
first robot in the array is the coach.

What Benefit: Smaller package size

**Comment by robocup-hl-tc** [comment]
That should not be done currently due to the fixed UDP Package Size. One would rather need to check if we can somehow solve the issue of seperating or specializing the protocol for the HL and SPL with other measures.
