### ISSUE TITLE
Ready state in free kick

### ISSUE THREAD

**Issue by MaikePaetzel** [RoboCup-Humanoid-TC/GameController#157]
I think there is an issue with what the gamecontroller sends when there is a freekick. In this example (from game TEST33), our player touches the ball with the hand and a direct_freekick is awarded to CIT (which is correct). But then it is shown "ready" as a phase when the robots should position themselves for the kick. I think the gamecontroller should send that the secondaryGameStateMode is 1 for placing (and show DIRECT_FREEKICK [1] in the UI). At least that is what the gamecontroller UI sends when I use it manually.  https://cloud.mafiasi.de/s/a6xmzYS96tEs5CZ

**Comment by MaikePaetzel** [comment]
I don't believe this is a bug on the GameController side. I cannot confirm from the GameController logs this happened, I cannot reproduce it locally and from the implementation of the GameController, it should not be possible to switch the main game state during a game interruption.

This needs a further confirmation that this problem actually is in the GameController before investigating it further.

**Comment by medrimonia** [comment]
It was confirmed that it was a display issue rather than an issue from the GC (linked to https://github.com/RoboCup-Humanoid-TC/webots/issues/170 )
