### ISSUE TITLE
Free Kick timeout

### ISSUE THREAD

**Issue by Gregwar** [RoboCup-Humanoid-TC/GameController#19]
Hello,
From the official rules:

    the ball is in play when it is kicked directly out of the penalty area (new): or 10 seconds after the referee gave the signal

If we want this rule to be applied, I think we need the 10 seconds counter to be visible in the Game Controller, and maybe also broadcasted

**Comment by sheepsy90** [comment]
Can you explain this a little more in detail?

**Comment by Gregwar** [comment]
Yes,

When there is a Free Kick, opponent robots should leave the 0.5m radius around the ball within 15 seconds. This is indeed handled by the GameController, changing the secondary game state and the 15 seconds are broadcasted on the secondary time.

However, after the free kick starts (when "execute free kick" is clicked), the opponent can't touch the ball unless it was touched or 10s are elapsed. Those 10s are not present in the Game Controller.

This situation is quite similar to the Kick Off, at the very begining of the game the team that doesn't kick off the ball can't enter the center circle within 10 seconds.

As teams, we can count this time ourself after the signal, but I think it would be nice having it in the GameController, and maybe consider introducing a braodcasted state for this.

**Comment by sheepsy90** [comment]
Okay - I was under the impression that a robot needs to recognise that the state changes from free kick to playing again and then count the 10 seconds for themselves or react to the ball moving (good indicator it was kicked)

Would this be at least a possibility?

**Comment by Gregwar** [comment]
Yes this is a possibility for the robots, however the human referees would still have to run manually a chronometer if they want to check that this rule is respected

**Comment by sheepsy90** [comment]
The main conflict I see by broadcasting the 10 seconds after the free kick that robot's need to 'ignore' this when the ball moved anyway right?

**Comment by sheepsy90** [comment]
Yes I agree but I guess that's actually the referees job to check that the robots don't violate the 10 seconds rule

**Comment by Gregwar** [comment]
> The main conflict I see by broadcasting the 10 seconds after the free kick that robot's need to 'ignore' this when the ball moved anyway right?

The same problem apply for the Kick Off, right?

**Comment by sheepsy90** [comment]
I don't know as I did not implemented anything in that area but it could very well be.

**Comment by sheepsy90** [comment]
@Gregwar I would like to keep the current version as the German Open are just around the corner where the 2017.1 version will be tested first. Then we can see further after we gathered more insight from that event. Do you agree to that strategy?

**Comment by Gregwar** [comment]
Ok, I'll be there with the Rhoban team next week ;)

**Comment by sheepsy90** [comment]
Thats cool :)
Then I hope for only a very small amount and well written bug reports :P

**Comment by robocup-hl-tc** [comment]
I do think it is useful to have the 10 seconds displayed in the GameController. The referees have to handle a lot already, so having this time counting down would help for sure. However, I don't think it should be broadcasted. The robots can keep track of the time themselves. 

It would be good if that's handled comparably in the kick-off and free-kick. I'm currently not completely sure how it's handled in the kick-off. But I believe the way it should be is that it's displayed for the referees, but not send to the robots.

**Comment by Gregwar** [comment]
During the kick off the time is displayed and available in the secondary secs field of the broadcast

**Comment by Gregwar** [comment]
Moreover, when the "execute free kick" button is pressed (signaling the end of the 15 secondes of preparing), we can't touche the ball for 10s, but can we enter the 50cm radius around it during this period?

**Comment by Gregwar** [comment]
What will happen if a team executes a free kick and kicks the ball before the 15s are over? (Before the "Execute free kick" button is pressed)

**Comment by sheepsy90** [comment]
I will close this ticket as the free kick is now being implemented in a three state system - if there is another issue with the timing please reopen or create a new ticket
