### ISSUE TITLE
Allow to start GameController from within Eclipse

### ISSUE THREAD

**Issue by klausdorer** [RoboCup-Humanoid-TC/GameController#20]
May be I did something wrong, but for me it did not work to clone the game controller, import it in eclipse and run it. It is not able to find the resources like config/spl/teams.cfg

The typical cure for this is to add the resources folder as source folder in eclipse. This has two problems here:

1. The dropins folder will then show compilation errors. Not sure if dropins is really properly located in the resources folder since it contains source files.

2. The files are still not found. To be able to have both, finding resources in source and jar, one should use getResourceAsStream() method. This would have to be changed at least at:
TeamsLoader.java (71)
`InputStream stream = getClass().getClassLoader().getResourceAsStream(PATH+dir+"/"+CONFIG);
Scanner s = new Scanner(stream);`
Teams.java (83)
`InputStream inStream = getClass().getClassLoader().getResourceAsStream(PATH+dir+"/"+CONFIG);
// InputStream inStream = new FileInputStream(PATH+dir+"/"+CONFIG);`
Teams.java (142)
`Helper dummy = new Helper();
InputStream inStream = dummy.getClass().getClassLoader().getResourceAsStream(PATH+Rules.league.leagueDirectory+"/"+CONFIG);`

With 2 changed the files are still not found when running as jar. The build process in build.xml would have to be changed to include the config folder in the classpath. I stopped here.

**Comment by sheepsy90** [comment]
Thanks for the feedback. The resource handling is a problem in the current version of the GC. I am currently trying to change a lot in the underlying structure as there are multiple places where those standard principals are violated.

I am personally using IntelliJ for programming. As soon as I finished the drop in mode refactoring and merged this we can have a look into other parts of refactoring.

We will leave this ticket open for now so we can fix that a little bit down the road.

**Comment by fthielke** [comment]
Actually, the GameController could always be started from within Eclipse.

We are building with Ant, which means that instead of using Eclipse's "Run as..." button, you have to right-click the build.xml, select "Run As" and click on "Ant Build".

The current project configuration makes this only build the jar files; if you also want to directly run the GameController, configure the target by clicking on the second option, "Ant Build...", and check the "run" target. There are also targets to directly run any of the other applications.

**Comment by sheepsy90** [comment]
I am developing the new features in IntelliJ  so I cant help much with run configuration. I suppose you want to run it in eclipse to use the debugger?

**Comment by klausdorer** [comment]
Yes, it would be for debugging. But again, this is a low priority issue. Our high level robot code is in Java which allows us to use the GameController classes directly from within our code for GameController communication (not the C++ wrapper).

**Comment by sheepsy90** [comment]
I see - any particular issue where I can help explain the software?
