### ISSUE TITLE
Compilation problem in Helper

### ISSUE THREAD

**Issue by klausdorer** [RoboCup-Humanoid-TC/GameController#21]
When cloning we get a compilation error in eclipse in class Helper.java on line

import org.junit.Rule;

The import is not needed and can be removed.

**Comment by sheepsy90** [comment]
Oh that's probably a side effect when I tried to put unit tests to the project. Will take care of this asap.

**Comment by sheepsy90** [comment]
Should be fixed once the pr is merged
