### ISSUE TITLE
Drop-In game: Dropped ball not implemented/no button

### ISSUE THREAD

**Issue by DualJ** [RoboCup-Humanoid-TC/GameController#26]
During a drop-in game there is no button for a dropped ball (rules pp. 661-685)

**Comment by sheepsy90** [comment]
Can someone verify that the functionality is present in an SPL drop in game?

**Comment by DualJ** [comment]
As far as BHuman knows: not, was only implemented for humanoid games

**Comment by sheepsy90** [comment]
Should work with the latest change
