### ISSUE TITLE
Drop-In game: not possible to switch sides of teams during setup

### ISSUE THREAD

**Issue by DualJ** [RoboCup-Humanoid-TC/GameController#27]
It should be possible during setup of a match to switch the sides of the teams to the corresponding sides of the field

**Comment by sheepsy90** [comment]
How is that solved in a regular game? I don't remember how it usually was working?

**Comment by sheepsy90** [comment]
Or is that the team selection?

**Comment by DualJ** [comment]
It is not possible to choose both teams on either side (in the opening dialog/team selection screen)

**Comment by sheepsy90** [comment]
This i label as enhancement - as the drop down removes the already selected team. Try set one side to none.

**Comment by sheepsy90** [comment]
Actually you are correct - just checked it myself - I need to investigate why this is not possible.

**Comment by sheepsy90** [comment]
The last commit should fix this issue
