### ISSUE TITLE
Drop-In game: Counting of individual points

### ISSUE THREAD

**Issue by robocup-hl-tc** [RoboCup-Humanoid-TC/GameController#28]
If a goal is scored by team A, only robots from team A who are not suffering from a penalty and are not in service should receive a point. Currently all of them receive a point.

**Comment by sheepsy90** [comment]
Does this mean all robots who actively are in game receive a point? So also all other penalties also restrict robots from receiving points?

**Comment by robocup-hl-tc** [comment]
Yes, robots who have any penalty do not receive a +1. However, they get a -1 if the goal is scored against them.

**Comment by sheepsy90** [comment]
Should be fixed with the last commit.
