### ISSUE TITLE
Regular / Drop-In game: Possibility to mark the goal keeper

### ISSUE THREAD

**Issue by robocup-hl-tc** [RoboCup-Humanoid-TC/GameController#29]
The goal keeper has special protection in the game and teams need to announce which of their players is the goal keeper. It would be good to be able to add a label for the robot currently being the goal keeper.

**Comment by sheepsy90** [comment]
Should this be just a UI feature or also broad casted via the protocol? Can it be changed all the time?

**Comment by robocup-hl-tc** [comment]
Only UI. Yes, can be changed.

**Comment by sheepsy90** [comment]
How critical is this feature? As it is more complex work in adding a concept to the GC. It is not complicated but rather complex

**Comment by robocup-hl-tc** [comment]
No need for an urgent fix.

**Comment by sheepsy90** [comment]
This feature became easier with the refactoring of the background UI composition. Still a question how critical it is.

**Comment by sheepsy90** [comment]
![screenshot from 2018-05-16 21-23-24](https://user-images.githubusercontent.com/595087/40139301-bdb19360-594f-11e8-8e71-e0a6c668d4fd.png)
