### ISSUE TITLE
Drop-In: Customizable number of players

### ISSUE THREAD

**Issue by robocup-hl-tc** [RoboCup-Humanoid-TC/GameController#30]
We should show up to six players for each team as in the regular games. It should be possible to mark either one or two of them as (sub), meaning they are not active in the game. Currently all five are always active, even if only five players participate.

**Comment by sheepsy90** [comment]
I am confused on this one - as far as I understood all players are playing within the game. What I would propose is to raise the number of players to seven and put two as substitue.

**Comment by robocup-hl-tc** [comment]
Drop-In games might be 5:5 or 4:4. This could be something you select in the opening dialogue.

**Comment by DualJ** [comment]
to be precise:rules 1536: "If there is an insufficient number of participants, games may be played 4 vs. 4 resp. 3 vs. 3 or 3 vs. 3 resp. 2 vs. 2 for KidSize resp. TeenSize."

**Comment by robocup-hl-tc** [comment]
This can be solved with a drop-down ranging from two to five players
