### ISSUE TITLE
Drop-In: Opening Dialogue

### ISSUE THREAD

**Issue by robocup-hl-tc** [RoboCup-Humanoid-TC/GameController#32]
Drop-In games cannot be knock-out games. So the checkbox should be removed. Since there is only one half time, automated color switching doesn't apply either. Checkbox can be removed as well.

**Comment by sheepsy90** [comment]
Here we need to check with compatibility with SPL. I am not sure how that works on their side. There is no refactored UI backend for the STartUp Chooser

**Comment by robocup-hl-tc** [comment]
In SPL drop-in, you don't have the checkboxes.
