### ISSUE TITLE
Drop-In: Exception thrown

### ISSUE THREAD

**Issue by robocup-hl-tc** [RoboCup-Humanoid-TC/GameController#35]
_Exception in thread "main" java.lang.StackOverflowError at controller.ui.ui.HL_DropIn.dispose(Unknown Source)_

Unfortunately not easy to reproduce, but thrown at some point and then very often in a row. Doesn't seem to affect the functionality, only printed in the console.

**Comment by sheepsy90** [comment]
Could not reproduce so far so will close this until it comes up again
