### ISSUE TITLE
Regular and Drop-In: Adding red and yellow cards per robot

### ISSUE THREAD

**Issue by robocup-hl-tc** [RoboCup-Humanoid-TC/GameController#38]
It should be possible to assign red and yellow cards for each robot individually. If a card is assigned, this should be send to the robots and shown in the UI.

**Comment by sheepsy90** [comment]
Needs some merging of the two components. This is mainly programming work, Merging the DropInTeamComponent and the YellowRedCardComponent

**Comment by sheepsy90** [comment]
Fixed
