### ISSUE TITLE
Make clear which team is on which side

### ISSUE THREAD

**Issue by sheepsy90** [RoboCup-Humanoid-TC/GameController#44]
Currently in the re factored version it is not entirely clear which team is which in the GameController during the game. There should be some beauty added again.

**Comment by Gregwar** [comment]
:+1:

**Comment by Gregwar** [comment]
Will it be OK for the competition?
I think this is important, we used it during our tests and it's currently unclear which team is where (moreover the teams are flipped in the 2nd half which make it more confusing without team names and colors visually)

**Comment by sheepsy90** [comment]
@Gregwar It is now done - you can have a look - it is not as nice as the old GC but I restructured the complete background code and made it component based instead of one giant super long 1000 line UI class. The result of this is that of course some UI prettifying is needed for next  year.

**Comment by Gregwar** [comment]
Thanks you, it's better like this!
