### ISSUE TITLE
Buttons stay "pressed" visually

### ISSUE THREAD

**Issue by Gregwar** [RoboCup-Humanoid-TC/GameController#48]
After I press a button like "Service" and then a robot, the "Service" button remains visually pressed like this:

![Pressed](https://img15.hostingpics.net/pics/675937pressed.png)

**Comment by sheepsy90** [comment]
I know :/ I couldn't figure out yet how this can be removed - I will try to make sure it works before the tournament

**Comment by sheepsy90** [comment]
Fixed

**Comment by Gregwar** [comment]
Super, thanks
