### ISSUE TITLE
Manually penalized

### ISSUE THREAD

**Issue by Gregwar** [RoboCup-Humanoid-TC/GameController#50]
Hello,
In the game controller return data, the robot can "manually penalize" itself
I don't really understand what does it means regarding the rules, is it a way that the robot can signal its own malfunctioning for instance?

**Comment by sheepsy90** [comment]
I think so - but i am not sure as well

**Comment by MaikePaetzel** [comment]
I think this is a way for robot handlers to manually penalize their robots when they were taken out of the game and have not received the penalty from the GameController yet. However, I think this is a feature from SPL and not from the HL league.
