### ISSUE TITLE
GameController doesn't end correctly in Windows

### ISSUE THREAD

**Issue by robocup-hl-tc** [RoboCup-Humanoid-TC/GameController#51]
We are running the GameController in Windows. When you close the GameController, you can't open it again because it says there is another instance already running. You have to manually end the javaw process in the Task Manager before you can start it again. It looks like when you close it by clicking on the "x" on the top right it doesn't shut down the process correctly. Would be excellent if that could be fixed.

**Comment by sheepsy90** [comment]
Done
