### ISSUE TITLE
Changes in free-kick secondary state order

### ISSUE THREAD

**Issue by robocup-hl-tc** [RoboCup-Humanoid-TC/GameController#59]
Currently, the GameController goes to "prepare free kick" first and counts down the 15 seconds and then goes to "freeze free kick". This is the wrong order! The following changes should therefore be made without changing the protocol (for direct, indirect free-kick and penalty kick):

1. In the UI, have the "freeze free-kick" first (without secondary game time) and then "prepare free kick"
2. Change the labels on the UI - instead of "freeze" have just "Free Kick" / "Indirect Free Kick" / "Penalty Kick"
3. Once you click on the button - instead of "prepare" have "Free Kick Ready" (the others accordingly)
4. Execute Free Kick stays as is.
5. Please change the description in the protocol and wiki as well, but do NOT change the actual bits that are send in each case.

**Comment by sheepsy90** [comment]
There is still a secondary clock being set to zero and yellow blinking while the ball is being put in position but that shouldn't be a big problem
