### ISSUE TITLE
Check if penalty is removed too quickly

### ISSUE THREAD

**Issue by robocup-hl-tc** [RoboCup-Humanoid-TC/GameController#60]
I'm not sure about this one, but today it seemed like the robots got the information that their penalty was removed already when the 30 seconds were finished counting down without the necessity for the GameController assistant to manually "free" the robot by clicking on it again. That shouldn't be the case - the robot should only get the signal after the button was pressed and is not blinking yellow anymore. This might not actually be the case and only observed by mistake, but please just confirm that this is not the case.

**Comment by sheepsy90** [comment]
Marked as big as I did not know where to look at it and it might take some more minutes

**Comment by sheepsy90** [comment]
It is actually not being removed prematurely - at least the right penalty is being set in the data that is used to build the UDP package
