### ISSUE TITLE
Secondary time in Free Kick state 1 (old "freeze") changes randomly

### ISSUE THREAD

**Issue by robocup-hl-tc** [RoboCup-Humanoid-TC/GameController#61]
It was reported that the secondary clock when you first click on "free kick" (which was the old "freeze state") keeps changing randomly and takes crazy values. This is not good, because even though it is not important in this game state, there might be teams listening to it and getting confused still. So if there is a fix for this (even a hot fix that just sets it to 0 hard coded) would be very helpful.

**Comment by sheepsy90** [comment]
I cannot reproduce this behavior
