### ISSUE TITLE
GameController goes to extended time even in normal mode

### ISSUE THREAD

**Issue by robocup-hl-tc** [RoboCup-Humanoid-TC/GameController#63]
Extended time and penalty shoot-outs are only possible in knock-out matches. Normal matches should not lead to time extension or penalty shoot-out.

**Comment by sheepsy90** [comment]
I don't get extended time in a normal game and yes the button for penalty shoots after two haves appear but if i tamper with the logic there before tomorrow it might break stuff so I currently suggest then to not press it.

**Comment by robocup-hl-tc** [comment]
It should appear, that is not a bug but a feature, because overtime is optional.

**Comment by sheepsy90** [comment]
I don't really understand this ticket still.

**Comment by sheepsy90** [comment]
See my last comment
