### ISSUE TITLE
Counting of points in Drop-In

### ISSUE THREAD

**Issue by robocup-hl-tc** [RoboCup-Humanoid-TC/GameController#67]
For some reason, after the game it said -8 on the team score, while it should have been -4. I couldn't reproduce it, but can you just make sure one more time that only if they suffer from a goal they get -1 point and for no other reason than that.

**Comment by sheepsy90** [comment]
What is the team score?

**Comment by sheepsy90** [comment]
I think I will close this as there seems to be no problem while investigation
