### ISSUE TITLE
Highlight Timout button as "clickable" and re-label

### ISSUE THREAD

**Issue by robocup-hl-tc** [RoboCup-Humanoid-TC/GameController#68]
When a timeout is taken, the button has to be clicked again to finish the timeout. This is not obvious from the button design, it looks "clicked" and more like a status information. Can you make them the same color as the other clickable robots and relabel as "Timeout Finish"

**Comment by sheepsy90** [comment]
I fixed the highlighting for the team timeout buttons but not for the referee - however all those buttons now got a different description when they are clickable vs. when they were clicked and need to be clicked again.
