### ISSUE TITLE
Drop-In: Points are counted wrong

### ISSUE THREAD

**Issue by robocup-hl-tc** [RoboCup-Humanoid-TC/GameController#72]
I can confirm now that there is still something wrong with counting the points for drop-in. In one situation, a robot was clearly penalized in the GameController but still received a point for scoring.

**Comment by sheepsy90** [comment]
Current working hypothesis is that blinking ready robots receive points even though they are still in penalty.

**Comment by sheepsy90** [comment]
When in dropin and scoring a goal the GC Assistent will get a help clock reminding them to add the score for the shooter manually.

**Comment by sheepsy90** [comment]
I need a reproducible report for what is wrong.
