### ISSUE TITLE
Macro conflicting with enum from ftdi.h library

### ISSUE THREAD

**Issue by anantanurag** [RoboCup-Humanoid-TC/GameController#73]
At RoboCupGameControlData.h:52:45: #define NONE                                0
conflicts with enum from ftdi.h
/usr/include/ftdi.h:27:64 - enum ftdi_parity_type { NONE=0, ODD=1, EVEN=2, MARK=3, SPACE=4 };

**Comment by MaikePaetzel** [comment]
I am closing this now - in case this is still an issue, please open another ticket with further elaborations.
