### ISSUE TITLE
2 vs 2 Drop-In games in AdultSize

### ISSUE THREAD

**Issue by MaikePaetzel** [RoboCup-Humanoid-TC/GameController#76]
For 2018, we need a game interface to play Drop-In games in AdultSize playing 2 vs 2

**Comment by whtqh** [comment]
We can get only one RobotInfo [0], and the RobotInfo[1] seems to be wrong...
using the newly updated GameController.

ERROR] [1560598598.686812822]: PENALTY[0]: 0
[ERROR] [1560598598.686852827]: PENALTY[1]: 195
[ERROR] [1560598598.686864006]: PENALTY[2]: 205
[ERROR] [1560598598.686872969]: PENALTY[3]: 5
[ERROR] [1560598598.686879959]: PENALTY[4]: 0
[ERROR] [1560598598.686890330]: PENALTY[5]: 0
[ INFO] [1560598598.686901154]: Game Type: Playoff
[ INFO] [1560598598.686910187]: Game State: Initial
[ INFO] [1560598598.686918926]: First half
[ INFO] [1560598598.686926553]: Kick Off Team: 25
[ INFO] [1560598598.686941103]: Secondary State: Normal
[ INFO] [1560598598.686952431]: Drop In Team: 0
[ INFO] [1560598598.686967766]: Drop In Time: 65535 s
[ INFO] [1560598598.686985524]: Remaining Time: 600 s
[ INFO] [1560598598.687000718]: Secondary Time: 0 s
[ INFO] [1560598598.687015216]: Score: THU 0 : 0 XXX 
[ INFO] [1560598598.687028661]: Penalty Shot: THU 0 : 0 XXX 
[ INFO] [1560598598.687043290]: Single Shots: THU 0 : 0 XXX

[ INFO] [1560598598.687058288]: A_Penalty: None
[ INFO] [1560598598.687071070]: A_Penalty: 0
[ INFO] [1560598598.687083847]: A_Time Until Unpenalized: 0 s
[ INFO] [1560598598.687096591]: A_Yellow Card: 0
[ INFO] [1560598598.687110028]: A_Red Card: 0

[ INFO] [1560598598.687124409]: B_Penalty: Unknown
[ INFO] [1560598598.687135421]: B_Penalty: 195
[ INFO] [1560598598.687147501]: B_Time Until Unpenalized: 126 s
[ INFO] [1560598598.687159314]: B_Yellow Card: 238
[ INFO] [1560598598.687169549]: B_Red Card: 12
