### ISSUE TITLE
Skip extra time in knock-out games

### ISSUE THREAD

**Issue by MaikePaetzel** [RoboCup-Humanoid-TC/GameController#78]
Not sure if that exists already, but in knock-out games the referee should be able to skip the extra time and move on to the penalty kicks right away

**Comment by sheepsy90** [comment]
@MaikePaetzel Currently in knock out games the game controller doesn't allow you to go in overtime for some reason - seems to not have been an issue - that of course means in knock out games you can directly go to penalty shoot out - however I suppose it should be from the extended times as well

**Comment by sheepsy90** [comment]
@MaikePaetzel Nevermind - the problem is that it is implemented that in a knock out game you can only go to overtime if both teams have the same score but the score is not 0 to 0
