### ISSUE TITLE
Java NoClassDefFoundError when running GameController

### ISSUE THREAD

**Issue by andylun1206** [RoboCup-Humanoid-TC/GameController#81]
I got a teamcomm/Config dependency issue when running `java -jar build/jar/GameController`. I solved it by fixing the `build.xml`. Just wondering if anyone is having the same issue when trying to run the GameController and whether if I should submit a PR to fix it.

**Comment by sheepsy90** [comment]
Hey Andy - I usually just build it with ant - the build technique is quite ancient but my java experience is limited in terms of moving the whole project to something like maven.

If you have a PR that fixes that I will test it with my IDE and merge it if it works.

**Comment by andylun1206** [comment]
I also used `ant` to build the Java app but it gave me an error when I tried to run it. It's just missing `teamcomm/Config` as a dependency. I will submit a PR to fix this.

**Comment by andylun1206** [comment]
@sheepsy90 Could I get access to push to this repository? Thanks!

**Comment by sheepsy90** [comment]
@andylun1206 Would be good if you could fork and PR. As I would need to contact some people to check how we deal with access management. So PR is probably faster :P

**Comment by andylun1206** [comment]
@sheepsy90 Never tried forking and submitting a PR. Thanks for letting me know about this!

PR #82 submitted.

**Comment by sheepsy90** [comment]
Then we can close this one right?
