### ISSUE TITLE
Stoppage, restart of play (throw-in, corner kick, goal kick)

### ISSUE THREAD

**Issue by medrimonia** [RoboCup-Humanoid-TC/GameController#88]
- Now, we need 3 buttons
  1. Throw-in
  2. Goal-kick
  3. Corner-Kick
- "Out" is not required anymore
- Information on the type of restart should be included in messages
- All those procedure need something similar to Free kicks (prepare + execute)

**Comment by diarodriguezva** [comment]
@medrimonia, the C++ headers need to be updated correspondingly, specifically the  	RoboCupGameControlData.h  Do we need a new version of the protocol ?

**Comment by medrimonia** [comment]
Your concern is raised in #95 I opened a PR which takes your comment into account. Thank you for pointing this.
