### ISSUE TITLE
Goal at Kick-off: which procedure?

### ISSUE THREAD

**Issue by medrimonia** [RoboCup-Humanoid-TC/GameController#90]
When robots with kick-off scores a goal directly at kick-off, kick-off is given to other team (see L675-677). I am not sure whether it's possible or not with the current game controller.

**Comment by MaikePaetzel** [comment]
This is not possible in the current implementation - particularly, changing kick-off is not allowed under these circumstances. Is this critical, @medrimonia ?

**Comment by medrimonia** [comment]
With the latest version of the rule, scoring a goal directly from a kick-off leads to a goal-kick so that should not be a problem at all anymore. We probably fixed the rules and I failed to close the issue.
