### ISSUE TITLE
Penalization behaviour

### ISSUE THREAD

**Issue by diarodriguezva** [RoboCup-Humanoid-TC/GameController#97]
I have noted three problems while testing the penalization (pickup/incapable, pushing, ball_manipulation) of the game controller:
1. The operator has to click twice on the robot player in order to start the penalization timers. This puts extra work and cognitive load to the operator, thus operator mistakes are more probable to happen. Suggestion: As soon as the player is clicked, the timer should start.
2.  While a robot is penalized, if the operator click on the player, the timer is restarted. I think this is not intuitive and may confuse the operators. Suggestion: if a player is clicked while being penalized, nothing should happen, if the timer has to be restarted for whatever reason, use the penalization button again.
3. Once a player has been penalized and the penalization is over (more than 30 seconds have passed), if the operator clicks on the player, the player got immediately penalized without any reason. This may be Critical !!!

**Comment by UHochberg** [comment]
I totally agree. None of our referees inuitively  understood this behaviour - and even if someone would, it is essential the referees tracks which robot has already been penalized and which robot is to be penelized for the first time. This will be very confusing.
There should be at least always the same procedure, not distinguishing between the first penalization and the next penalizations.

**Comment by diarodriguezva** [comment]
Hi @sheepsy90, is there any progress or comments on this regard ?

**Comment by medrimonia** [comment]
Sorry for the time elapsed before providing an answer.

For 1 and 2 if I did understand well your comments, it refers to changes in the rules which are explained in the referee training video and in the rulebook. Now robots start serving the 30 seconds penalty once they are read to enter the field again, not at the moment of the infraction. Therefore, that's normal behavior. It will be clearly explained during referee training tomorrow.

Number 3 is critical, I do fully agree. We will do our best to fix it before the beginning of the competition. However, keep in mind that it is possible to cancel the reset of the penalty.

**Comment by sheepsy90** [comment]
@medrimonia I roughly figured out where this bug is coming from but I have a hard time fixing it as I don't exaclty know how the thought is behind this double click to start the penalty: Here is what I think happens. When the robot is penalized a flag is set that it is penalized and when clicking the second time it starts the clock. However when the clock is up the robot's flag for penalization is still set and clicking on the robot button restarts the clock.

The problem lies somewhere around:

`  }
        else if (data.isServingPenalty[side][number]) {// If robot is currently serving penalty, reset penalty time
            data.whenPenalized[side][number] = data.getTime();
            Log.state(data, "Resetting penalty for " + data.team[side].teamColor + " " + (number+1));
        }`

in the Robot.java

**Comment by medrimonia** [comment]
This should be ok, even if I find the fix a little bit dirty since cleaning the flag's of the robot (in the GUI), should be done by a time.
